Testing
NataJenkins/toDoList pull request #2
Opened 2021-05-31 19:58 UTC by NataJenkins

Unit Testing for To do application using Jest

2021-05-31 20:20 UTC, umararshadbut requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] Remove the `console.log`. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/console_log_requirement.png) from Pathwright)
- [x] Please move the test directory into the root directory.
- [ ]  Please add the test instruction in the README file.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Please add the `.vscode` into the `.gitignore`.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**Umair**
**Happy Coding :smiley:**

2021-06-01 09:06 UTC, bellom requested changes
## Hi @NataJenkins  :clap: 

# Status: Changes Required! ♻️ 

**Kindly attend to the previous reviewer request;**

**_Could it be from my end 🤔, I see no changes._**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-06-01 09:09 UTC, bellom requested changes

2021-06-01 09:09 UTC, bellom commented on src/projects.js
> +  console.log(JSON.parse(localStorage.getItem("projects")));
Kindly remove this line.

2021-06-01 09:09 UTC, bellom commented on src/test/projects.test.js
> +  console.log(testProject);
Remove this line.

2021-06-01 09:09 UTC, bellom commented on src/test/tasks.test.js
> +  console.log(testTask);
Remove this line.

2021-06-01 09:09 UTC, bellom commented on README.md
> +1. Go to the [repository page](https://github.com/pointerish/Books/).
Kindly add the test instruction in the README file(That is; how to run the test)

2021-06-01 12:49 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-06-21 23:06 UTC, merged